version: '3'

services:
  svelte_server:
    build: .
    restart: always
    volumes:
      - "./database:/database"
    environment:
      - DATABASE_FILE=/database/database.sqlite
    ports:
      - "5072:4173"

