version: '3'

services:
  svelte_server:
    build: 
      context: .
      args:
        - DATABASE_FILE=/database/database.sqlite
    environment:
      - DATABASE_FILE=/database/database.sqlite
    restart: always
    volumes:
      - "./database:/database"
    ports:
      - "5072:4173"

